### ISSUE TITLE
Can't cache custom scalar Date data

### ISSUE THREAD

**Issue by lity** [mercurius-js/cache#115]
Mercurius-cache works well with Graphql built-in types, but when I used it to cache a field which has a custom scalar Date sub-field, error occurred.

---
Uncaught (in promise) Error: value.getTime is not a function
---

The scalar Date is defined like this : https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/#example-the-date-scalar, and I used redis as storage.

I guess the reason is that when cache is hit, Date type data fetched from redis as a string,  but it is not converted to js Date type.

How to cache custom scalar Date, please help, thanks.

**Comment by simone-sanfratello** [comment]
It's surely something we need to investigate

Thanks for reporting!

**Comment by Poiuytrezay1** [comment]
I have the same problem just now with no custom scalar and only dateScalarMode: 'timestamp' options on GraphQL.

**Comment by simone-sanfratello** [comment]
@Poiuytrezay1 @lity could you please provide an example?

**Comment by lity** [comment]
I have resolved this problem, here is my solution, code snippet.

-----------------typedefs-----------------

scalar Date

type User {
    id:ID!
    name:String!
    regtime:Date!
}

-----------------resolvers-----------------

export default {
    Query: {
        users: async (_, { id }) => {
            ...
            return await UserModel.find({_id:id})
        },
    },
    Date: new GraphQLScalarType({
        name: 'Date',
        description: 'Date custom scalar type',
        parseValue: value => new Date(value),
        ///////////////////////////////////////////LINE BELOW IS KEY////////////////////////////////////////////////////////////
        serialize: value => typeof value === 'object' ? value.getTime() : new Date(value).getTime(),
        ///////////////////////////////////////////LINE ABOVE IS KEY////////////////////////////////////////////////////////////
        parseLiteral: ast => ast.kind === Kind.INT ? new Date(+ast.value) : null,
    }),
}

-----------------mercurius-cache-----------------
        app.register(mercuriusCache, {
            storage: {
                type: 'redis',
                options: {
                    client: redisClient,
                    invalidation: true,
                }
            },
            ttl: 60 * 2,
            policy: {
                Query: {
                    ...
                },
                Mutation: {
                    ...
                }
            }
        })

============================================
When Redis is used as mercurius-cache storage, custom scalar Date data will be converted to string type, so it can be save in Redis. 
If cache is hit, Date data is fetched from Redis as string, it needs to be converted from string to js Date type. This is the key point.
The conclusion is, if developer uses custom Scalar type and Redis is used as mercurius-cache storage, developer should make sure scalar type can be converted from string correctly.
