### ISSUE TITLE
Exception not properly handled

### ISSUE THREAD

**Issue by Poiuytrezay1** [mercurius-js/cache#116]
Most likely linked to https://github.com/mercurius-js/cache/issues/110.

The resulting error I get from GraphQL is: 
`Cannot return null for non-nullable field`

When it should be:
`Unauthorized`

**Explanation (and my investigation):**
I have a JWT guard that throws an UnauthorizedError when a user is not properly authenticated. This guard seems to be called the first time a GraphQL field is resolved (i.e. from originalFieldResolver). This exception is not caught and rethrown by **mercurius-cache**, which causes it to be caught by async-cache-dedupe which then calls the onError callback without rethrowing the error (the query promise is chained, and has a catch error). Because of this, GraphQL continue its execution as if nothing happened and therefore throws _another_ error later (due to having no data).

**Dependencies:**

fastify: 4.9.2
mercurius: 11.1.0
mercurius-cache: 3.0.1
Node.js: 16.13.2

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Poiuytrezay1** [comment]
The reproducible example is the same as the one linked. Here is a slightly modified one:
```
import Fastify from "fastify";
import mercurius from "mercurius";
import mercuriusCache from "mercurius-cache";

const schema = `#graphql
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello(parent, args, context) {
      console.log("Exception called but not handled");
      throw new Error("Error I want to see in GraphQL");
    },
  },
};

const app = Fastify();

await app.register(mercurius, {
  schema,
  resolvers,
  graphiql: true,
});

await app.register(mercuriusCache, {
  ttl: 2, // seconds
  all: true,
  storage: {
    type: "memory",
    options: {
      size: 2048,
    },
  },
});

app.listen({ port: 3002, host: "0.0.0.0" });
```

The response is:
{
    "data": {
        "hello": null
    }
}

Instead of an error

**Comment by mcollina** [comment]
@simone-sanfratello could you take a look?

**Comment by simone-sanfratello** [comment]
Probably next week

**Comment by simone-sanfratello** [comment]
solved, sorry for delay
