### ISSUE TITLE
not working with fastify-cli project.

### ISSUE THREAD

**Issue by vamshi9666** [mercurius-js/cache#124]
I have a project setup using fastify-cli and bob-ts for typescript. 

Mercurius cache is not getting registered when running project in dev/prod mode. 
But when i ran `fastify-fli export ` command and run generated `server.js`. Cache is working as expected.

I put some console.log's in lib code and found out 'onReady' hook is never being called. Possible issue with cli itself

library code `cache.js`
`
 app.log.warn('mercurius-cache is ready')
  
  app.addHook('onReady', async () => {
    app.log.warn('mercurius-cache is loaded');
  
    app.graphql.cache.refresh()
    report.refresh()
  })

`

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by vamshi9666** [comment]
unable to reproduce. This issue can be closed.
