### ISSUE TITLE
Responses which fail GraphQL schema validation are stored in the cache.

### ISSUE THREAD

**Issue by dualbus** [mercurius-js/cache#128]
Hello,

I'd like to start by acknowledging that I understand that this might be "working as-designed". I'd still like to know if you have any suggestions on how to deal with the following situation.

The issue: mercurius-cache will store a value in the cache before the value goes through GraphQL validation, and this causes subsequent queries that use the same cache key to get a cached error response. The only option I see to prevent this is to set an `onResolution` hook in Mercurius that invalidates the cache for a given query.

To reproduce this, please install the following dependencies:

```
$ cat package.json 
{
  "name": "mercurius-cache-skip-cache-on-graphql-error",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "fastify": "4.13.0",
    "graphql": "16.6.0",
    "mercurius": "12.2.0",
    "mercurius-cache": "4.0.0"
  }
}
```

And execute the following script:

```
$ cat index.js 
'use strict'

const fastify = require('fastify')
const mercurius = require('mercurius')
const cache = require('mercurius-cache')

const app = fastify({ logger: true })

const schema = `
  type Query {
    add(x: Int, y: Int): Int
    hello: String
  }
`

const resolvers = {
  Query: {
    async add (_, { x, y }, { reply }) {
      reply.log.info('add called')

      return 'not a number'
    }
  }
}

app.register(mercurius, {
  schema,
  resolvers
})


// cache query "add" responses for 10 seconds
app.register(cache, {
  ttl: 10,
  policy: {
    Query: {
      add: true
      // note: it cache "add" but it doesn't cache "hello"
    }
  }
})

app.listen({ port: 3000, host: '127.0.0.1' })
```

In a separate Bash shell, execute:

```
for i in {1..2}; do curl -X POST -H 'content-type: application/json' -d '{ "query": "{ add(x: 2, y: 2) }" }' localhost:3000/graphql; echo; done
```

These are the observed results:

```
ebustamante@debian:~/mercurius-cache-skip-cache-on-graphql-error$ node index.js 
{"level":30,"time":1677525493784,"pid":655752,"hostname":"debian","msg":"Server listening at http://127.0.0.1:3000"}
{"level":30,"time":1677525499460,"pid":655752,"hostname":"debian","reqId":"req-1","req":{"method":"POST","url":"/graphql","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":44568},"msg":"incoming request"}
{"level":30,"time":1677525499468,"pid":655752,"hostname":"debian","reqId":"req-1","msg":"add called"} 
{"level":30,"time":1677525499469,"pid":655752,"hostname":"debian","reqId":"req-1","err":{"type":"GraphQLError","message":"Int cannot represent non-integer value: \"not a number\"","stack":"GraphQLError: Int cannot represent non-integer value: \"not a number\"\n    at GraphQLScalarType.serialize (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/type/scalars.js:61:13)\n    at completeLeafValue (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/execution/execute.js:738:39)\n    at completeValue (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/execution/execute.js:619:12)\n    at /home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/execution/execute.js:486:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at async Object.fastifyGraphQl [as graphql] (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/mercurius/index.js:531:23)","path":["add"],"locations":[{"line":1,"column":3}],"extensions":{}},"msg":"Int cannot represent non-integer value: \"not a number\""}
{"level":30,"time":1677525499472,"pid":655752,"hostname":"debian","reqId":"req-1","res":{"statusCode":200},"responseTime":12.557700157165527,"msg":"request completed"}
{"level":30,"time":1677525499480,"pid":655752,"hostname":"debian","reqId":"req-2","req":{"method":"POST","url":"/graphql","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":44584},"msg":"incoming request"}
{"level":30,"time":1677525499482,"pid":655752,"hostname":"debian","reqId":"req-2","err":{"type":"GraphQLError","message":"Int cannot represent non-integer value: \"not a number\"","stack":"GraphQLError: Int cannot represent non-integer value: \"not a number\"\n    at GraphQLScalarType.serialize (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/type/scalars.js:61:13)\n    at completeLeafValue (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/execution/execute.js:738:39)\n    at completeValue (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/execution/execute.js:619:12)\n    at /home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/graphql/execution/execute.js:486:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at async Object.fastifyGraphQl [as graphql] (/home/ebustamante/mercurius-cache-skip-cache-on-graphql-error/node_modules/mercurius/index.js:531:23)","path":["add"],"locations":[{"line":1,"column":3}],"extensions":{}},"msg":"Int cannot represent non-integer value: \"not a number\""}
{"level":30,"time":1677525499482,"pid":655752,"hostname":"debian","reqId":"req-2","res":{"statusCode":200},"responseTime":1.6182003021240234,"msg":"request completed"}
```

And

```
ebustamante@debian:~/mercurius-cache-skip-cache-on-graphql-error$ for i in {1..2}; do curl -X POST -H 'content-type: application/json' -d '{ "query": "{ add(x: 2, y: 2) }" }' localhost:3000/graphql; echo; done 
{"data":{"add":null},"errors":[{"message":"Int cannot represent non-integer value: \"not a number\"","locations":[{"line":1,"column":3}],"path":["add"]}]}
{"data":{"add":null},"errors":[{"message":"Int cannot represent non-integer value: \"not a number\"","locations":[{"line":1,"column":3}],"path":["add"]}]}
```

Notice that for the second request `add called` is not logged, as it's read from the cache.

As per my initial comment, I understand that this is perhaps working as designed. `mercurius-cache` wraps resolvers individually, so when graphql-js resolves a value (in node_modules/graphql/execution/execute.js, see snippet below), `mercurius-cache` doesn't know early enough about type validation errors.

```
  try {
    // Build a JS object of arguments from the field.arguments AST, using the
    // variables scope to fulfill any variable references.
    // TODO: find a way to memoize, in case this field is within a List type.
    const args = (0, _values.getArgumentValues)(
      fieldDef,
      fieldNodes[0],
      exeContext.variableValues,
    ); // The resolve function's optional third argument is a context value that
    // is provided to every resolve function within an execution. It is commonly
    // used to represent an authenticated user, or request-specific caches.

    const contextValue = exeContext.contextValue;
    const result = resolveFn(source, args, contextValue, info);   /* Ed's note: mercurius-cache will store the value in the cache here */
    let completed;

    if ((0, _isPromise.isPromise)(result)) {
      completed = result.then((resolved) =>
        completeValue(exeContext, returnType, fieldNodes, info, path, resolved), /* Ed's note: Graphql-js throws an error here, because the string value does not serialize to an integer type */
      );
    } else {
      completed = completeValue(
        exeContext,
        returnType,
        fieldNodes,
        info,
        path,
        result,
      );
    }
```

To give an example situation where this might be an issue: Suppose we have a GraphQL service that assembles responses from multiple upstream services. If any of these upstream services introduces a bug that causes a breaking change in their response format, that may lead to type validation errors. Without mercurius-cache, this issue will be resolved as soon as the upstream service reverts the breaking change. But with mercurius-cache, the cache will keep these invalid values for the duration of the TTL.

In the example scenario, there are several strategies that could help reduce the impact: (a) Ensure TTLs are low enough to allow for quick recovery after such breaking change, (b) validate input from the upstream service at the resolver error and throw an error if the validation fails. I don't like (a), because it reduces the effectiveness of the cache. I don't like (b), because we're essentially duplicating the validation that we already get from graphql-js.

Without introducing changes to mercurius-cache / async-cache-dedupe, I believe the only option that we have to avoid caching values that fail GraphQL validation is to setup an `onResolution` hook that invalidates the cache on GraphQL errors. This seems a bit expensive.

Another option that does require changes to async-cache-dedupe and mercurius-cache would be to add the ability to defer calls to `storage.set` in `_wrapFunction` by accepting a sort of "cache flush" callback. The caller can then decide at which point during the request lifecycle to execute the call to `storage.set`. This seems a bit complicated to me, and potentially error prone. But I can't think of any other options.

**Comment by simone-sanfratello** [comment]
Thanks for reporting so in details!

I'd say to use the `skip` function if possible and run the validation in there, since `skip` already has the result of the resolver but hasn't already cached it.

Do you think it could work?

**Comment by dualbus** [comment]
Thanks for your quick response, Simone!

> I'd say to use the skip function and run the validation in there

Thanks, I'll give that a try. My guess is that it'll work, but the drawback is that now we'll have to run the GraphQL value validation twice. So it may introduce a (perhaps too small to notice?) performance issue.

**Comment by simone-sanfratello** [comment]
That's true, validation will run twice. Can you memoize that function? Maybe with `async-cache-dedupe`?

@mcollina wdyt?

**Comment by mcollina** [comment]
> To give an example situation where this might be an issue: Suppose we have a GraphQL service that assembles responses from multiple upstream services. If any of these upstream services introduces a bug that causes a breaking change in their response format, that may lead to type validation errors. Without mercurius-cache, this issue will be resolved as soon as the upstream service reverts the breaking change. But with mercurius-cache, the cache will keep these invalid values for the duration of the TTL.

This is working as designed. Note that the vast majority of the benefit from this module comes from the deduplication, not a long TTL. There isn't much we can do to address this, minus deferring setting the value in the cache _after_ the graphql request is completed - this would be a significant major change and I don't think we have the bandwidth to do.

**Comment by Puppo** [comment]
Hi @mcollina and @simone-sanfratello 
I would help with this issue.

The idea that I have in mind is this without changing too much codebase. In the function where the code retrieves the data from the original resolve (in the cache.define), we could save in the response an array with a list of functions to invalidate the cache items created during its execution. Then we can subscribe the plugin to the onResolution hook, and on this hook, check if there are errors and, in case of error, check if there is the array in the response and in case run all functions to invalidate the keys affected. In case of many queries in the same request, this approach clears all the queries affected.
 I prepared a draft here for feedback #146
