### ISSUE TITLE
Request to Bump mercurius-cache to v7.0.0

### ISSUE THREAD

**Issue by acoBOYZ** [mercurius-js/cache#173]
Hi there,

I saw that an attempt was made to bump mercurius-cache to version 7.0.0, but it didn’t quite go through. I was hoping this could be revisited, as the v7.0.0 update is important for compatibility with the latest versions of Fastify.

Thanks so much for all the hard work on maintaining this project – it’s truly invaluable!

**Comment by simoneb** [comment]
Can you explain what you mean? Are you trying to bump v7 in your app but having troubles, or something else?

**Comment by jimmy-guzman** [comment]
Could the confusion come from v7.0.0 not being tagged as `latest` but with `next` instead?

**Comment by acoBOYZ** [comment]
Latest version solved my problem thanks. My problem was I can not use previous version of mercurius-cache with latest version of fastify (v5.0.0).
