### ISSUE TITLE
allow `fastify` v5

### ISSUE THREAD

**Issue by jimmy-guzman** [mercurius-js/cache#174]
Looks like `fastify` and `fastify-plugin` v5 versions are already being used. Is it possible to allow `fastify ` [v5 instead of 4.x](https://github.com/mercurius-js/cache/blob/main/index.js#L53) to prevent unexpected `fastify` version error.

**Comment by luthfi-hh** [comment]
I have the same issue when trying to update to Fastify v5.
cc: @mcollina 
```
FastifyError [FST_ERR_PLUGIN_VERSION_MISMATCH]: fastify-plugin: index-auto-1 - expected '4.x' fastify version, '5.0.0' is installed
```

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by jimmy-guzman** [comment]
> Would you like to send a PR?

Yeah I can do that.

**Comment by mcollina** [comment]
Thanks

**Comment by mcollina** [comment]
Shipped a release
