### ISSUE TITLE
Add options validation

### ISSUE THREAD

**Issue by simone-sanfratello** [mercurius-js/cache#27]
Add options validation, it should check:
- options values
- `mercurius` is already registered
- validate policy entries are consistent to gql schema

**Comment by TomasTM** [comment]
Assignee: @TomasTM

**Comment by mcollina** [comment]
Go for it!

**Comment by simoneb** [comment]
Here's some guidance about how to implement this, as @TomasTM is not yet familiar with the codebase and mercurius in general.

1. options values: @simone-sanfratello I'm not aware of fastify plugins which validate options, is there any reason why we should do it here? If we want to do it for any reason, I guess fluent-json-schema and ajv is what we would go with
2. mercurius is already registered: we should use fastify's plugin mechanism to do this, exposed by [fastify-plugin](https://github.com/fastify/fastify-plugin). See how it's done [here](https://github.com/nearform/mercurius-apollo-tracing/blob/main/src/index.ts#L106)
3. validate policy entries are consistent with gql schema: this is one I would not know how to do exactly. Basically the idea is that the policies need to match the schema. E.g. if you specify a policy on a resolver called `add`, that resolver should exist in the schema

I believe that:

1. is not strictly necessary
2. is easy and we should do it
3. might be tricky to do but I would definitely look into it and if anybody has inputs about how to match two schemas to see that they "intersect" please share!

**Comment by simone-sanfratello** [comment]
>     1. options values: @simone-sanfratello I'm not aware of fastify plugins which validate options, is there any reason why we should do it here? If we want to do it for any reason, I guess fluent-json-schema and ajv is what we would go with

imo inputs should be validated on public methods, so we can use values safely internally
for example this is the validation for mercurius options https://github.com/mercurius-js/mercurius/blob/master/index.js#L67
I'm happy with every solution, I prefer schema validation too, but I don't have strong opinion
not really agree this is not necessary, it prevents runtime errors and basic issues like typos

>     3. validate policy entries are consistent with gql schema: this is one I would not know how to do exactly. Basically the idea is that the policies need to match the schema. E.g. if you specify a policy on a resolver called `add`, that resolver should exist in the schema

as the first implementation, we could just match options policy keys resolvers or schema AST

anyway, happy to help @TomasTM  anytime!
