### ISSUE TITLE
Redis storage

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/cache#29]
As titled.

**Comment by simone-sanfratello** [comment]
working on this as it is related to #30

**Comment by simoneb** [comment]
@simone-sanfratello are you actively working on this and #30?

**Comment by simone-sanfratello** [comment]
@simoneb yes https://github.com/mercurius-js/cache/pull/48

**Comment by simone-sanfratello** [comment]
done in https://github.com/mercurius-js/cache/pull/48
