### ISSUE TITLE
Make default onError log the error with a debug levle

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/cache#58]
Let's change this default implementation. It would significantly better if by default we logged this error as `debug`.

_Originally posted by @mcollina in https://github.com/mercurius-js/cache/pull/48#discussion_r783975298_

**Comment by simone-sanfratello** [comment]
https://github.com/mercurius-js/cache/pull/48#discussion_r783975298

**Comment by jhonrocha** [comment]
I will take a look on this.
