### ISSUE TITLE
Add some Redis tests

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/cache#59]
The should explicitly target invalidations

**Comment by simone-sanfratello** [comment]
how about replicate these https://github.com/mcollina/async-cache-dedupe/blob/main/test/storage-redis.test.js#L362 in gql context? or you have more specific cases?

**Comment by mcollina** [comment]
Yes exactly

**Comment by jhonrocha** [comment]
Hi! I will take a look on this.

**Comment by jhonrocha** [comment]
@mcollina the above PR is adding tests for:

- should remove storage keys by references
- should not remove storage key by not existing reference
- should invalidate more than one reference at once

I am using [ioreids-mock](https://www.npmjs.com/package/ioredis-mock), is that okay?

The other option would be to configure Redis on CI action.
