### ISSUE TITLE
listen to `onError` of `async-cache-dedupe`

### ISSUE THREAD

**Issue by simone-sanfratello** [mercurius-js/cache#66]
on `v1.1.0` `async-cache-dedupe` has it's own `onError` event, so we should listen at it and forward to `onError` event of `cache`

also add an error counter on report

**Comment by jhonrocha** [comment]
Hi! I will take a look on this.

**Comment by jhonrocha** [comment]
@simone-sanfratello Do you have suggestion on what should we use as `prefix` and `fieldName` when passing the error from `dedupe` to `onError` ?

**Comment by simone-sanfratello** [comment]
you can use them if you have, or expose the information you have
